### ISSUE TITLE
Boss Checklist doesn't load images

### ISSUE THREAD

**Issue by DrYoshiyahu** [Voxelse/LiveSplit.Terraria#1]
Opening the Boss Checklist gives [the webpage with no images to click](https://cdn.discordapp.com/attachments/374153827169075202/784003776851476510/unknown.png). I assume it's some compatibility issue with with whatever archaic middle-ages internet browser LiveSplit is using to display pages, and [my code](https://github.com/DrYoshiyahu/terraria-boss-checklist) for the webapp, but I have no idea what the problem is.

I've spent hours tonight just trying to get the webpage to load by adding polyfills for practically every function in the code, but usually LiveSplit at least gave me a script error so I could see where the problem was. This time, I'm not getting any script errors at all—just no images loading.

It's particularly annoying because I know it's not a problem experienced universally.

**Comment by Voxelse** [comment]
To display the web page, I'm using a WebBrowser Form which is using a wrapper of Internet Explorer.
On my side it uses IE11 but it may depend on the installed version on the computer.

I personally don't have any problem (and Max Overpower either) so I don't know how I could help with that.

By the way, instead of making a whole lot of test commits on the main branch of your repo, you can build a custom version of the component with the local URL of your changes so you can do your test without affecting the release branch.

**Comment by Voxelse** [comment]
And just for reference what is your OS and IE version?

I'm pretty sure you have an older IE (between 7-10) so the missing functions might come from that.

If you don't manage to fix it for the pre-IE11 versions, I might look at some alternatives to load web pages (probably with chromium) as IE is widely unsupported.

**Comment by DrYoshiyahu** [comment]
Gosh, the night I've had. After your first comment, I figured you might be right: that it might depend on the version installed on the PC, so I did some searching around.

Turns out, Internet Explorer wasn't installed *at all* on my PC in any capacity (trust me, I scoured the depths of the computer's system files) so after some digging around the internet (and accidentally trying to install Windows 7 versions of IE), I worked out how to install it on Windows 10 (no, you can't just download an `.exe` and run that).

But after installing it, the autosplitter still wasn't displaying the images, even after I tried deleting the local files related to the autosplitter so they could be hard-refreshed. So, I deleted LiveSplit and downloaded a fresh copy (don't worry, I kept my config file) and finally it worked. 😌

Thanks again for all your work. I have no idea what you did, but you turned my baby little app into a proper program, and I'm extremely grateful for it! 💜
