### ISSUE TITLE
for 1.4.1.1 isn't working

### ISSUE THREAD

**Issue by NaiveStorm** [Voxelse/LiveSplit.Terraria#3]
it starts the timer but it doesn't split, do you have any backup of the last version?

**Comment by Voxelse** [comment]
You can download the previous version [here](https://github.com/Voxelse/LiveSplit.Terraria/raw/77f65e433bb9a7ef8be11401f425f6c7d8fa809f/Components/LiveSplit.Terraria.dll) and override the new version in the 'Components' folder of LiveSplit.

I heard that people were running on the latest version so I haven't added the support to older versions.
Though, if some people are running on older versions, I can probably add them to work as well.

**Comment by NaiveStorm** [comment]
ok tysm
