### ISSUE TITLE
Doesn't work in 1.4.3, new boss Deerclops

### ISSUE THREAD

**Issue by kengho** [Voxelse/LiveSplit.Terraria#4]
1. Autosplitter doesn't work in Terraia 1.4.3 or newer. Fails both autostart and splitting.
2. Also there's a new boss Deerclops (https://terraria.fandom.com/wiki/Deerclops) and it would be nice to have autosplitter for it. It might fit well right between Skeletron and Wall of Flesh in the list, and killing it should be required for "All Bosses" split.

**Comment by Voxelse** [comment]
Updated: 5fa9d9aa7fa206c7b0ff5dac510e036deef84a60
If you have any issues let me know and I'll try to fix them.

**Comment by kengho** [comment]
Thank you very much, everything seems to work just fine.
